### ISSUE TITLE
Add Install script to CMakelists.

### ISSUE THREAD

**Issue by TimZaman** [glassechidna/zxing-cpp#23]
For apple and linux, add something like this to Cmakelists?

INSTALL(FILES _build/libzxing.a  DESTINATION /usr/local/lib/ )
INSTALL(FILES _build/zxing       DESTINATION /usr/local/bin/ )
INSTALL(DIRECTORY core/src/ DESTINATION /usr/local/include FILES_MATCHING PATTERN "*.h" )

**Comment by Benjamin-Dobell** [comment]
@TimZaman Please submit a pull request.

**Comment by TimZaman** [comment]
Sorry but i hacked around too much for that, but this is one addition that would be profitable for anyone. I don't really see the point of libiconv either. Gives me a lot of hassle.

**Comment by Benjamin-Dobell** [comment]
You can always stage partial file changes with:

```
git add -p CMakeLists.txt
```

and pick the sections you want to commit.

Honestly, I just took over maintaining this project because no-one else was. I don't claim anything in the project makes sense; quite frankly it all looks pretty awful!

I'm just maintaining this project in a central location so everyone can benefit from fixes/improvements made by others. I don't have a lot of time to dedicate to this so I'm relying on this being a real community effort i.e. I'm just the gate keeper.

As such, pull requests are more than welcome. If you think we can ditch libiconv and have a pull request (with corresponding explanation) to back it up, then go nuts.

**Comment by Benjamin-Dobell** [comment]
Closed by https://github.com/glassechidna/zxing-cpp/pull/31
